name: day4
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  quiver: ^2.1.3
  path: ^1.8.0
  collection: ^1.14.0
  file_parser:
    path: ../file_parser

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
